<<<<<<< HEAD
name: paRtilhando códigos de R
title: uma página por Sara Mortara
 left:
    - text: "First Observations"
      href: praticas/pratica0_introducao_ao_R.html
description: >
    aqui eu compartilho o que apanhei nos últimos anos de R e modelagem estatística.

theme: jekyll-theme-midnight
     
# Social
twitter: #@MortaraSara #Add your Twitter
github: @saramortara


# Comments
discus-identifier: jtemporal

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]

=======
theme: jekyll-theme-midnight
>>>>>>> parent of 64a6465... adding specifications to config
